/*
 * Map Matching
 *
 * With the Map Matching service you can assign GPS positions to road segments on a digital map.
 *
 * The version of the OpenAPI document: 1.7
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.mapmatch.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.mapmatch.Model
{
    /// <summary>
    /// Defines PositionsResultType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PositionsResultType
    {
        /// <summary>
        /// Enum GEOMETRY for value: GEOMETRY
        /// </summary>
        [EnumMember(Value = "GEOMETRY")]
        GEOMETRY = 1,

        /// <summary>
        /// Enum SEGMENT_LOCATION_DESCRIPTORS for value: SEGMENT_LOCATION_DESCRIPTORS
        /// </summary>
        [EnumMember(Value = "SEGMENT_LOCATION_DESCRIPTORS")]
        SEGMENT_LOCATION_DESCRIPTORS = 2,

        /// <summary>
        /// Enum SEGMENT_ATTRIBUTES for value: SEGMENT_ATTRIBUTES
        /// </summary>
        [EnumMember(Value = "SEGMENT_ATTRIBUTES")]
        SEGMENT_ATTRIBUTES = 3,

        /// <summary>
        /// Enum LOW_EMISSION_ZONES for value: LOW_EMISSION_ZONES
        /// </summary>
        [EnumMember(Value = "LOW_EMISSION_ZONES")]
        LOW_EMISSION_ZONES = 4,

        /// <summary>
        /// Enum TOLL for value: TOLL
        /// </summary>
        [EnumMember(Value = "TOLL")]
        TOLL = 5
    }

}
