/* tslint:disable */
/* eslint-disable */
/**
 * Map Matching
 * With the Map Matching service you can assign GPS positions to road segments on a digital map.
 *
 * The version of the OpenAPI document: 1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CausingError
 */
export interface CausingError {
    /**
     * A human readable message that describes the error.
     * @type {string}
     * @memberof CausingError
     */
    description: string;
    /**
     * A constant string that can be used to identify this error class programmatically.
     * 
     * If additional information is available for an errorCode, it will be provided as key-value pairs with the parameter **details**. The keys available for a specific errorCode are documented directly with the errorCode. Unless stated otherwise, the values are of type string.
     * 
     * As an example, the following errorCode provides one key-value pair in the **details**. The key is called **value**.
     * * `GENERAL_INVALID_VALUE` - A parameter is set to an invalid value.
     *   * `value` - The invalid value.
     * 
     * Note that additional errorCodes as well as the **details** of existing errorCodes may be added at any time. Furthermore, the **description** may change at any time.  
     * 
     * **Error codes for** `GENERAL_RESOURCE_NOT_FOUND`
     * * `GENERAL_INVALID_ID` - No resource exists for the provided ID.  
     *   * `value` - The ID for which no resource exists. 
     * 
     * **Error codes for** `GENERAL_VALIDATION_ERROR`
     * * `GENERAL_INVALID_VALUE` - A parameter is set to an invalid value.  
     *   * `value` - The invalid value.  
     * * `GENERAL_UNRECOGNIZED_PARAMETER` - A parameter is unknown.
     * * `GENERAL_MISSING_PARAMETER` - A required parameter is missing.
     * * `GENERAL_DUPLICATE_PARAMETER` - A parameter is duplicated.  
     * * `GENERAL_PATTERN_VIOLATED` - The value of a string parameter does not satisfy the required pattern.
     *   * `pattern` - The pattern.
     * * `GENERAL_TYPE_VIOLATED` - The value of a parameter has an invalid type.
     *   * `type` - The type.
     * * `GENERAL_FORMAT_VIOLATED` - The value of a parameter has an invalid format.
     *   * `format` - The format.
     * * `GENERAL_MINIMUM_VALUE_VIOLATED` - The minimum value of a parameter is violated.  
     *   * `minimumValue` - The minimum value (integer or double).  
     * * `GENERAL_MAXIMUM_VALUE_VIOLATED` - The maximum value of a parameter is violated.  
     *   * `maximumValue` - The maximum value (integer or double).  .
     * * `GENERAL_ENUM_VIOLATED` - The value of a parameter is not one of the specified enum values.
     *   * `enum` - The allowed enum values.
     * * `GENERAL_MINIMUM_ITEMS_VIOLATED` - The minimum number of items of an array is violated.  
     *   * `minimumItems` - The minimum number of items (integer).  
     * * `GENERAL_MAXIMUM_ITEMS_VIOLATED` - The maximum number of items of an array is violated.  
     *   * `maximumItems` - The maximum number of items (integer).
     * * `MAP_MATCH_TIMESTAMPS_ALL_OR_NONE_VIOLATED` - Either all or none of the timestamps must be set.  
     *   * `numberOfDefinedTimestamps` - Total number of input positions with timestamp.  
     *   * `numberOfUndefinedTimestamps` - Total number of input positions without timestamp.  
     * * `MAP_MATCH_TIMESTAMPS_ASCENDING_VIOLATED` - Timestamps are not ascending.  
     *   * `numberOfNotAscendingTimestamps` - Total number of not ascending timestamps.  
     *   * `indexOfFirstViolatedTimestamp` - Index of the first not ascending timestamp.  
     *   * `timestamp` - Value of the first not ascending timestamp.  
     *   * `previousTimestamp` - Value of the timestamp before the first not ascending one.
     * 
     * **Error codes for** `MAP_MATCH_RESTRICTION_EXCEEDED`
     * 
     * * `MAP_MATCH_TOO_MANY_POSITIONS` - The request contains too many positions.  
     *   * `limit` - The maximum allowed number of positions for a single request (integer).
     * @type {string}
     * @memberof CausingError
     */
    errorCode: string;
    /**
     * The name of the affected query or path parameter or a JSONPath to the affected property of the request.
     * @type {string}
     * @memberof CausingError
     */
    parameter?: string;
    /**
     * Additional properties specific to this error class.
     * @type {{ [key: string]: any; }}
     * @memberof CausingError
     */
    details?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CausingError interface.
 */
export function instanceOfCausingError(value: object): value is CausingError {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('errorCode' in value) || value['errorCode'] === undefined) return false;
    return true;
}

export function CausingErrorFromJSON(json: any): CausingError {
    return CausingErrorFromJSONTyped(json, false);
}

export function CausingErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): CausingError {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'errorCode': json['errorCode'],
        'parameter': json['parameter'] == null ? undefined : json['parameter'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function CausingErrorToJSON(value?: CausingError | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'errorCode': value['errorCode'],
        'parameter': value['parameter'],
        'details': value['details'],
    };
}

