/* tslint:disable */
/* eslint-disable */
/**
 * Map Matching
 * With the Map Matching service you can assign GPS positions to road segments on a digital map.
 *
 * The version of the OpenAPI document: 1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The emission standard of the vehicle valid in the European Union.
 * @export
 */
export const EmissionStandard = {
    NONE: 'NONE',
    EURO_0: 'EURO_0',
    EURO_1: 'EURO_1',
    EURO_2: 'EURO_2',
    EURO_3: 'EURO_3',
    EURO_4: 'EURO_4',
    EURO_5: 'EURO_5',
    EURO_EEV: 'EURO_EEV',
    EURO_6: 'EURO_6',
    EURO_6C: 'EURO_6C',
    EURO_6D_TEMP: 'EURO_6D_TEMP',
    EURO_6D: 'EURO_6D',
    EURO_6E: 'EURO_6E',
    EURO_7: 'EURO_7'
} as const;
export type EmissionStandard = typeof EmissionStandard[keyof typeof EmissionStandard];


export function instanceOfEmissionStandard(value: any): boolean {
    for (const key in EmissionStandard) {
        if (Object.prototype.hasOwnProperty.call(EmissionStandard, key)) {
            if (EmissionStandard[key as keyof typeof EmissionStandard] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EmissionStandardFromJSON(json: any): EmissionStandard {
    return EmissionStandardFromJSONTyped(json, false);
}

export function EmissionStandardFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmissionStandard {
    return json as EmissionStandard;
}

export function EmissionStandardToJSON(value?: EmissionStandard | null): any {
    return value as any;
}

