/* tslint:disable */
/* eslint-disable */
/**
 * Map Matching
 * With the Map Matching service you can assign GPS positions to road segments on a digital map.
 *
 * The version of the OpenAPI document: 1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MatchType } from './MatchType';
import {
    MatchTypeFromJSON,
    MatchTypeFromJSONTyped,
    MatchTypeToJSON,
} from './MatchType';
import type { SegmentAttributes } from './SegmentAttributes';
import {
    SegmentAttributesFromJSON,
    SegmentAttributesFromJSONTyped,
    SegmentAttributesToJSON,
} from './SegmentAttributes';

/**
 * Detailed information about a position on a track matched on a map.
 * @export
 * @interface MatchedTrackPosition
 */
export interface MatchedTrackPosition {
    /**
     * 
     * @type {MatchType}
     * @memberof MatchedTrackPosition
     */
    matchType: MatchType;
    /**
     * Time defined according to [RFC 3339](https://tools.ietf.org/html/rfc3339) when the position was passed.
     * @type {Date}
     * @memberof MatchedTrackPosition
     */
    timestamp?: Date;
    /**
     * The travel distance [m] from the previous position. It is available only if MatchedTrackPosition.matchType is MATCH\_SUCCESSFUL.
     * @type {number}
     * @memberof MatchedTrackPosition
     */
    distanceFromPreviousMatch?: number;
    /**
     * The latitude value in degrees (WGS84/EPSG:4326) from south to north. This refers to the coordinates on the segment to which the input position matches. It is available only if MatchedTrackPosition.matchType is MATCH\_SUCCESSFUL.
     * @type {number}
     * @memberof MatchedTrackPosition
     */
    latitude?: number;
    /**
     * The longitude value in degrees (WGS84/EPSG:4326) from west to east. This refers to the coordinates on the segment to which the input position matches. It is available only if MatchedTrackPosition.matchType is MATCH\_SUCCESSFUL.
     * @type {number}
     * @memberof MatchedTrackPosition
     */
    longitude?: number;
    /**
     * The geometry of the matched segment as a GeoJSON representation. Coordinates are always present in WGS84 (EPSG:4326). It is available only if MatchedTrackPosition.matchType is MATCH\_SUCCESSFUL.
     * @type {string}
     * @memberof MatchedTrackPosition
     */
    segmentGeometry?: string;
    /**
     * The straight-line distance (Euclidean distance) [m] from the input position to the matching segment. It is available only if MatchedTrackPosition.matchType is MATCH\_SUCCESSFUL.
     * @type {number}
     * @memberof MatchedTrackPosition
     */
    matchDistance?: number;
    /**
     * The difference in degrees \[°\] between the angle of the heading of the input position and the angle of the matching segment. This difference is always smaller than the straight angle.  It is available only if MatchedTrackPosition.matchType is MATCH\_SUCCESSFUL.
     * @type {number}
     * @memberof MatchedTrackPosition
     */
    angleDifference?: number;
    /**
     * 
     * @type {SegmentAttributes}
     * @memberof MatchedTrackPosition
     */
    segmentAttributes?: SegmentAttributes;
}



/**
 * Check if a given object implements the MatchedTrackPosition interface.
 */
export function instanceOfMatchedTrackPosition(value: object): value is MatchedTrackPosition {
    if (!('matchType' in value) || value['matchType'] === undefined) return false;
    return true;
}

export function MatchedTrackPositionFromJSON(json: any): MatchedTrackPosition {
    return MatchedTrackPositionFromJSONTyped(json, false);
}

export function MatchedTrackPositionFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchedTrackPosition {
    if (json == null) {
        return json;
    }
    return {
        
        'matchType': MatchTypeFromJSON(json['matchType']),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'distanceFromPreviousMatch': json['distanceFromPreviousMatch'] == null ? undefined : json['distanceFromPreviousMatch'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'segmentGeometry': json['segmentGeometry'] == null ? undefined : json['segmentGeometry'],
        'matchDistance': json['matchDistance'] == null ? undefined : json['matchDistance'],
        'angleDifference': json['angleDifference'] == null ? undefined : json['angleDifference'],
        'segmentAttributes': json['segmentAttributes'] == null ? undefined : SegmentAttributesFromJSON(json['segmentAttributes']),
    };
}

export function MatchedTrackPositionToJSON(value?: MatchedTrackPosition | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'matchType': MatchTypeToJSON(value['matchType']),
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'distanceFromPreviousMatch': value['distanceFromPreviousMatch'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'segmentGeometry': value['segmentGeometry'],
        'matchDistance': value['matchDistance'],
        'angleDifference': value['angleDifference'],
        'segmentAttributes': SegmentAttributesToJSON(value['segmentAttributes']),
    };
}

