/* tslint:disable */
/* eslint-disable */
/**
 * Map Matching
 * With the Map Matching service you can assign GPS positions to road segments on a digital map.
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseFromJSONTyped,
    ErrorResponseToJSON,
} from './ErrorResponse';
import {
    MatchedTrack,
    MatchedTrackFromJSON,
    MatchedTrackFromJSONTyped,
    MatchedTrackToJSON,
} from './MatchedTrack';
import {
    MatchingStatus,
    MatchingStatusFromJSON,
    MatchingStatusFromJSONTyped,
    MatchingStatusToJSON,
} from './MatchingStatus';
import {
    Warning,
    WarningFromJSON,
    WarningFromJSONTyped,
    WarningToJSON,
} from './Warning';

/**
 * Contains the results of a matching calculation. If the 'status' is 'RUNNING', the matching calculation is still running and no further properties are set. If the 'status' is 'SUCCEEDED', the matching result is present as property 'matchedTrack'. If the 'status' is 'FAILED', the failure result is present as property 'error'.
 * @export
 * @interface MatchingResponse
 */
export interface MatchingResponse {
    /**
     * 
     * @type {MatchingStatus}
     * @memberof MatchingResponse
     */
    status?: MatchingStatus;
    /**
     * 
     * @type {MatchedTrack}
     * @memberof MatchingResponse
     */
    matchedTrack?: MatchedTrack;
    /**
     * 
     * @type {ErrorResponse}
     * @memberof MatchingResponse
     */
    error?: ErrorResponse;
    /**
     * A list of warnings concerning the validity of the result.
     * @type {Array<Warning>}
     * @memberof MatchingResponse
     */
    warnings?: Array<Warning>;
}

export function MatchingResponseFromJSON(json: any): MatchingResponse {
    return MatchingResponseFromJSONTyped(json, false);
}

export function MatchingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchingResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : MatchingStatusFromJSON(json['status']),
        'matchedTrack': !exists(json, 'matchedTrack') ? undefined : MatchedTrackFromJSON(json['matchedTrack']),
        'error': !exists(json, 'error') ? undefined : ErrorResponseFromJSON(json['error']),
        'warnings': !exists(json, 'warnings') ? undefined : ((json['warnings'] as Array<any>).map(WarningFromJSON)),
    };
}

export function MatchingResponseToJSON(value?: MatchingResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': MatchingStatusToJSON(value.status),
        'matchedTrack': MatchedTrackToJSON(value.matchedTrack),
        'error': ErrorResponseToJSON(value.error),
        'warnings': value.warnings === undefined ? undefined : ((value.warnings as Array<any>).map(WarningToJSON)),
    };
}

