/* tslint:disable */
/* eslint-disable */
/**
 * Map Matching
 * With the Map Matching service you can assign GPS positions to road segments on a digital map.
 *
 * The version of the OpenAPI document: 1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Describes the toll properties of a road segment.
 * @export
 * @interface Toll
 */
export interface Toll {
    /**
     * List of all vehicle types for which a toll is due on a road section.  
     * Available values are:  "ALL_VEHICLES", "BUS", "CAR", "CARPOOL", "DELIVERY_TRUCK", "MOTORCYCLE", "TAXI", "THROUGH_TRAFFIC", "TRUCK", "PEDESTRIAN", "EMERGENCY_VEHICLE".  
     * This list can be extended at any time, clients should handle unknown values properly.
     * @type {Array<string>}
     * @memberof Toll
     */
    vehicleCategories?: Array<string>;
}

/**
 * Check if a given object implements the Toll interface.
 */
export function instanceOfToll(value: object): value is Toll {
    return true;
}

export function TollFromJSON(json: any): Toll {
    return TollFromJSONTyped(json, false);
}

export function TollFromJSONTyped(json: any, ignoreDiscriminator: boolean): Toll {
    if (json == null) {
        return json;
    }
    return {
        
        'vehicleCategories': json['vehicleCategories'] == null ? undefined : json['vehicleCategories'],
    };
}

export function TollToJSON(value?: Toll | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'vehicleCategories': value['vehicleCategories'],
    };
}

