/* tslint:disable */
/* eslint-disable */
/**
 * Map Matching
 * With the Map Matching service you can assign GPS positions to road segments on a digital map.
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TrackPosition,
    TrackPositionFromJSON,
    TrackPositionFromJSONTyped,
    TrackPositionToJSON,
} from './TrackPosition';

/**
 * Contains positions to be matched as a track on a map.
 * @export
 * @interface Track
 */
export interface Track {
    /**
     * 
     * @type {Array<TrackPosition>}
     * @memberof Track
     */
    positions: Array<TrackPosition>;
}

export function TrackFromJSON(json: any): Track {
    return TrackFromJSONTyped(json, false);
}

export function TrackFromJSONTyped(json: any, ignoreDiscriminator: boolean): Track {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'positions': ((json['positions'] as Array<any>).map(TrackPositionFromJSON)),
    };
}

export function TrackToJSON(value?: Track | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'positions': ((value.positions as Array<any>).map(TrackPositionToJSON)),
    };
}

