/* tslint:disable */
/* eslint-disable */
/**
 * Map Matching
 * With the Map Matching service you can assign GPS positions to road segments on a digital map.
 *
 * The version of the OpenAPI document: 1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrackPosition } from './TrackPosition';
import {
    TrackPositionFromJSON,
    TrackPositionFromJSONTyped,
    TrackPositionToJSON,
} from './TrackPosition';

/**
 * Contains positions to be matched as a track on a map.
 * @export
 * @interface Track
 */
export interface Track {
    /**
     * The positions to be matched as a track on a map.
     * @type {Array<TrackPosition>}
     * @memberof Track
     */
    positions: Array<TrackPosition>;
}

/**
 * Check if a given object implements the Track interface.
 */
export function instanceOfTrack(value: object): value is Track {
    if (!('positions' in value) || value['positions'] === undefined) return false;
    return true;
}

export function TrackFromJSON(json: any): Track {
    return TrackFromJSONTyped(json, false);
}

export function TrackFromJSONTyped(json: any, ignoreDiscriminator: boolean): Track {
    if (json == null) {
        return json;
    }
    return {
        
        'positions': ((json['positions'] as Array<any>).map(TrackPositionFromJSON)),
    };
}

export function TrackToJSON(value?: Track | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'positions': ((value['positions'] as Array<any>).map(TrackPositionToJSON)),
    };
}

