/*
 * Map Matching
 * With the Map Matching service you can assign GPS positions to road segments on a digital map.
 *
 * The version of the OpenAPI document: 1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ptvgroup.developer.client.mapmatch.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import io.swagger.annotations.ApiModel;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gives information on the result of this match, i.e. whether the position was matched successfully or whether the position is considered as part of the track or not.    * &#x60;MATCH_SUCCESSFUL&#x60; - The position was matched successfully.    * &#x60;MATCH_FAILED&#x60; - The position could not be matched.    * &#x60;NOT_CONSIDERED&#x60; - The position was not considered.
 */
public enum MatchType {
  
  MATCH_SUCCESSFUL("MATCH_SUCCESSFUL"),
  
  MATCH_FAILED("MATCH_FAILED"),
  
  NOT_CONSIDERED("NOT_CONSIDERED");

  private String value;

  MatchType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static MatchType fromValue(String value) {
    for (MatchType b : MatchType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

